FROM mcr.microsoft.com/dotnet/sdk:8.0 AS builder
ENV ASPNETCORE_URLS http://+:5000
RUN mkdir /app
WORKDIR /app
COPY app.csproj ./
RUN dotnet restore
COPY . .
RUN dotnet publish --output /app/ --configuration Release

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=builder /app .
EXPOSE 5000
CMD dotnet app.dll
